//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public Nullable<int> ProvindsId { get; set; }
        public Nullable<int> DistrictsId { get; set; }
        public Nullable<int> WardsId { get; set; }
    
        public virtual District District { get; set; }
        public virtual Provind Provind { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
